[profile.default]
solc = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'solady/=lib/solady/src/',
    'shipyard-core/=lib/shipyard-core/src/',
    'create2-helpers/=lib/create2-helpers/script/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
